FROM ubuntu:16.04

COPY . /app
WORKDIR /app

# install java
RUN apt-get update && apt-get install default-jre -y

RUN apt-get install apt-transport-https ca-certificates -y

# install sbt
RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
RUN apt-get update && apt-get install sbt -y
RUN sbt sbtVersion

CMD ["sbt", "run"]
